version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: hgunified-web:v1
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - /app/node_modules # Prevents local node_modules from overwriting container ones
    environment:
      - NODE_ENV=development
    networks:
      - hgunified-web-network

networks:
  hgunified-web-network:
    driver: bridge